### ISSUE TITLE
[FEATURE] Discord Server

### ISSUE THREAD

**Issue by actuallyexeon** [Nyson-Programing-Language/nyson#5]
I was thinking about a Discord server related to this language for people to discuss things in, I think it would be easier to talk about Nyson's code and syntax in a Discord server then GitHub Discussions. And if you do make a Discord make the link not expire, Thanks.

**Comment by AMTitan** [comment]
So we made one I will update it on the docs and on here but the link right now is https://discord.gg/qDznKHuM
